version: '3.8'
services:
  docling-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    volumes:
      - ./config:/app/config
      - ./scripts:/app/scripts
      - ./tests:/app/tests
    environment:
      FLASK_APP: main.py
      FLASK_RUN_HOST: 0.0.0.0
    command: python -u /app/scripts/start_api.py # Force unbuffered output pour les logs
    restart: unless-stopped